//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Account", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại bước trước.
        /// </summary>
        internal static string BackPrevStep {
            get {
                return ResourceManager.GetString("BackPrevStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        internal static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string BtnConfirm {
            get {
                return ResourceManager.GetString("BtnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi yêu cầu.
        /// </summary>
        internal static string BtnSendRequest {
            get {
                return ResourceManager.GetString("BtnSendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kiểm tra.
        /// </summary>
        internal static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi hạn mức.
        /// </summary>
        internal static string ChangeLimitation {
            get {
                return ResourceManager.GetString("ChangeLimitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công, vui lòng đăng nhập lại.
        /// </summary>
        internal static string ChangePassSuccess {
            get {
                return ResourceManager.GetString("ChangePassSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ Email.
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emai nhận OTP.
        /// </summary>
        internal static string EmailGetSecureCode {
            get {
                return ResourceManager.GetString("EmailGetSecureCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã xác thực.
        /// </summary>
        internal static string EnterVerifyCode {
            get {
                return ResourceManager.GetString("EnterVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        internal static string ForgotPass {
            get {
                return ResourceManager.GetString("ForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to để lấy mã xác thực. OTPcó hiệu lực trong 30 giây..
        /// </summary>
        internal static string getVerifyCode {
            get {
                return ResourceManager.GetString("getVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn mức.
        /// </summary>
        internal static string Limitation {
            get {
                return ResourceManager.GetString("Limitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn mức mới.
        /// </summary>
        internal static string LimitationNew {
            get {
                return ResourceManager.GetString("LimitationNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn mức muốn đăng ký.
        /// </summary>
        internal static string LimitationRegister {
            get {
                return ResourceManager.GetString("LimitationRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại nhận OTP.
        /// </summary>
        internal static string MobileReceiveSecure {
            get {
                return ResourceManager.GetString("MobileReceiveSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn mức OTP là số tiền tối thiểu cho một giao dịch mà bạn muốn sử dụng dịch vụ bảo mật OTP.
        /// </summary>
        internal static string NoteLimitSecure {
            get {
                return ResourceManager.GetString("NoteLimitSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn mức OTP là số tiền tối thiểu cho một giao dịch mà bạn muốn sử dụng dịch vụ bảo mật OTP.
        /// </summary>
        internal static string NoteOTP1 {
            get {
                return ResourceManager.GetString("NoteOTP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng tải ứng dụng và làm theo hướng dẫn để đăng ký bảo mật.
        /// </summary>
        internal static string NoteOTP2 {
            get {
                return ResourceManager.GetString("NoteOTP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống sẽ gọi cho bạn để gửi mã OTP để xác nhận đăng ký.
        /// </summary>
        internal static string NoteOTP3 {
            get {
                return ResourceManager.GetString("NoteOTP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Với mỗi giao dịch, khách hàng phải sử dụng Ứng dụng.
        /// </summary>
        internal static string NoteOTPApp {
            get {
                return ResourceManager.GetString("NoteOTPApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Với mỗi giao dịch, hệ thống sẽ gửi một mã OTP đến Email.
        /// </summary>
        internal static string NoteOTPEmail {
            get {
                return ResourceManager.GetString("NoteOTPEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Với mỗi giao dịch, hệ thống sẽ gửi một mã OTP qua SMS đến số điện thoại.
        /// </summary>
        internal static string NoteOTPSMS {
            get {
                return ResourceManager.GetString("NoteOTPSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Với mỗi giao dịch, hệ thống sẽ gọi điện và gửi mã xác thực OTP đến số điện thoại.
        /// </summary>
        internal static string NoteOTPVoice {
            get {
                return ResourceManager.GetString("NoteOTPVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không nhận được mã, vui lòng soạn tin &lt;strong class=&quot;danger&quot;&gt;P365 BM&lt;/strong&gt; gửi &lt;strong class=&quot;danger&quot;&gt;8100&lt;/strong&gt; &lt;span class=&quot;warning&quot;&gt;(1.500 VNĐ/SMS)&lt;/span&gt;.
        /// </summary>
        internal static string NoteSecureOTPSMS {
            get {
                return ResourceManager.GetString("NoteSecureOTPSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã để xác thực đổi mật khẩu..
        /// </summary>
        internal static string PleaseEnterCode {
            get {
                return ResourceManager.GetString("PleaseEnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký bảo mật OTP.
        /// </summary>
        internal static string RegisterOTP {
            get {
                return ResourceManager.GetString("RegisterOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu mới.
        /// </summary>
        internal static string RenewPassword {
            get {
                return ResourceManager.GetString("RenewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận lại OTP.
        /// </summary>
        internal static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy lại mật khẩu qua Email.
        /// </summary>
        internal static string ResetPassViaEmail {
            get {
                return ResourceManager.GetString("ResetPassViaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy mật khẩu qua SMS.
        /// </summary>
        internal static string ResetPassViaSMS {
            get {
                return ResourceManager.GetString("ResetPassViaSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy lại mật khẩu qua tổng đài hỗ trợ.
        /// </summary>
        internal static string ResetPassViaSupport {
            get {
                return ResourceManager.GetString("ResetPassViaSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy lại mật khẩu.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã đổi mật khẩu thành công, popup tự đóng sau &lt;span id=&quot;countdwn&quot;&gt;5&lt;/span&gt;s, tự động quay về trang đăng nhập.
        /// </summary>
        internal static string ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 đến 18 ký tự.
        /// </summary>
        internal static string RulePassword1 {
            get {
                return ResourceManager.GetString("RulePassword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cả chữ và số.
        /// </summary>
        internal static string RulePassword2 {
            get {
                return ResourceManager.GetString("RulePassword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo mật.
        /// </summary>
        internal static string Secure {
            get {
                return ResourceManager.GetString("Secure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức bảo mật.
        /// </summary>
        internal static string SecureType {
            get {
                return ResourceManager.GetString("SecureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gửi.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt bảo mật.
        /// </summary>
        internal static string SetupSecure {
            get {
                return ResourceManager.GetString("SetupSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một mã xác thực đã được gửi đến điện thoại.
        /// </summary>
        internal static string StringMsg1 {
            get {
                return ResourceManager.GetString("StringMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không nhận được mã, vui lòng soạn tin &lt;strong class=&quot;danger&quot;&gt;P365 MK&lt;/strong&gt; gửi &lt;strong class=&quot;danger&quot;&gt;8100&lt;/strong&gt; &lt;span class=&quot;warning&quot;&gt;(1.500 VNĐ/SMS)&lt;/span&gt;.
        /// </summary>
        internal static string StringMsg2 {
            get {
                return ResourceManager.GetString("StringMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một mã xác thực đã được gửi đến địa chỉ email.
        /// </summary>
        internal static string StringMsg3 {
            get {
                return ResourceManager.GetString("StringMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý khách vui lòng bấm nút Nhận mã để nhận mã xác thực. Nếu không nhận được mã, soạn tin &lt;strong class=&quot;danger&quot;&gt;P365 MK&lt;/strong&gt; gửi &lt;strong class=&quot;danger&quot;&gt;8100&lt;/strong&gt; (1.500 đ/SMS).
        /// </summary>
        internal static string StringMsg4 {
            get {
                return ResourceManager.GetString("StringMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soạn tin.
        /// </summary>
        internal static string TextSMS {
            get {
                return ResourceManager.GetString("TextSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực.
        /// </summary>
        internal static string VerifyCode {
            get {
                return ResourceManager.GetString("VerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qua Email.
        /// </summary>
        internal static string ViaEmail {
            get {
                return ResourceManager.GetString("ViaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qua SMS.
        /// </summary>
        internal static string ViaSms {
            get {
                return ResourceManager.GetString("ViaSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qua tổng đài.
        /// </summary>
        internal static string ViaSupport {
            get {
                return ResourceManager.GetString("ViaSupport", resourceCulture);
            }
        }
    }
}
