//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Account_info {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account_info() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Account_info", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        internal static string Acc_btnChangePass {
            get {
                return ResourceManager.GetString("Acc_btnChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin ví điện tử.
        /// </summary>
        internal static string Acc_InfoWallet {
            get {
                return ResourceManager.GetString("Acc_InfoWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản.
        /// </summary>
        internal static string btn_account {
            get {
                return ResourceManager.GetString("btn_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản.
        /// </summary>
        internal static string btn_AccountInfo {
            get {
                return ResourceManager.GetString("btn_AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng thực.
        /// </summary>
        internal static string btn_Authenticate {
            get {
                return ResourceManager.GetString("btn_Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi.
        /// </summary>
        internal static string btn_change {
            get {
                return ResourceManager.GetString("btn_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhập thông tin.
        /// </summary>
        internal static string btn_changeAccInfo {
            get {
                return ResourceManager.GetString("btn_changeAccInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi hạn mức.
        /// </summary>
        internal static string btn_ChangeMinAmount {
            get {
                return ResourceManager.GetString("btn_ChangeMinAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi bảo mật.
        /// </summary>
        internal static string btn_ChangeSecure {
            get {
                return ResourceManager.GetString("btn_ChangeSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string btn_delete {
            get {
                return ResourceManager.GetString("btn_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử giao dịch.
        /// </summary>
        internal static string btn_History {
            get {
                return ResourceManager.GetString("btn_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string btn_home {
            get {
                return ResourceManager.GetString("btn_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        internal static string btn_Logout {
            get {
                return ResourceManager.GetString("btn_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi lại.
        /// </summary>
        internal static string btn_Resend {
            get {
                return ResourceManager.GetString("btn_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi yêu cầu.
        /// </summary>
        internal static string btn_SendRequest {
            get {
                return ResourceManager.GetString("btn_SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt bảo mật.
        /// </summary>
        internal static string btn_SetupSecure {
            get {
                return ResourceManager.GetString("btn_SetupSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhập.
        /// </summary>
        internal static string btn_update {
            get {
                return ResourceManager.GetString("btn_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực.
        /// </summary>
        internal static string btn_Verify {
            get {
                return ResourceManager.GetString("btn_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        internal static string lbl_account {
            get {
                return ResourceManager.GetString("lbl_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại tài khoản.
        /// </summary>
        internal static string lbl_accType {
            get {
                return ResourceManager.GetString("lbl_accType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản nghiệp vụ.
        /// </summary>
        internal static string lbl_accType0 {
            get {
                return ResourceManager.GetString("lbl_accType0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản cá nhân.
        /// </summary>
        internal static string lbl_accType1 {
            get {
                return ResourceManager.GetString("lbl_accType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản doanh nghiệp.
        /// </summary>
        internal static string lbl_accType2 {
            get {
                return ResourceManager.GetString("lbl_accType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string lbl_address {
            get {
                return ResourceManager.GetString("lbl_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư khả dụng.
        /// </summary>
        internal static string lbl_availableBalance {
            get {
                return ResourceManager.GetString("lbl_availableBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư ví.
        /// </summary>
        internal static string lbl_balance {
            get {
                return ResourceManager.GetString("lbl_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        internal static string lbl_birthday {
            get {
                return ResourceManager.GetString("lbl_birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng thực tài khoản.
        /// </summary>
        internal static string lbl_certificate {
            get {
                return ResourceManager.GetString("lbl_certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi Email.
        /// </summary>
        internal static string lbl_changeEmail {
            get {
                return ResourceManager.GetString("lbl_changeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin cá nhân.
        /// </summary>
        internal static string lbl_CustomerInfo {
            get {
                return ResourceManager.GetString("lbl_CustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lbl_email {
            get {
                return ResourceManager.GetString("lbl_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập email mới.
        /// </summary>
        internal static string lbl_enterEmail {
            get {
                return ResourceManager.GetString("lbl_enterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dư đóng băng.
        /// </summary>
        internal static string lbl_frozenBalance {
            get {
                return ResourceManager.GetString("lbl_frozenBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        internal static string lbl_fullname {
            get {
                return ResourceManager.GetString("lbl_fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        internal static string lbl_gender {
            get {
                return ResourceManager.GetString("lbl_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        internal static string lbl_gender1 {
            get {
                return ResourceManager.GetString("lbl_gender1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        internal static string lbl_gender2 {
            get {
                return ResourceManager.GetString("lbl_gender2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string lbl_header_eng {
            get {
                return ResourceManager.GetString("lbl_header_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nội dung cần tìm kiếm.
        /// </summary>
        internal static string lbl_header_textSearch {
            get {
                return ResourceManager.GetString("lbl_header_textSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        internal static string lbl_header_vi {
            get {
                return ResourceManager.GetString("lbl_header_vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin số dư.
        /// </summary>
        internal static string lbl_InfoBalance {
            get {
                return ResourceManager.GetString("lbl_InfoBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin bảo mật.
        /// </summary>
        internal static string lbl_infoSecure {
            get {
                return ResourceManager.GetString("lbl_infoSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghề nghiệp.
        /// </summary>
        internal static string lbl_job {
            get {
                return ResourceManager.GetString("lbl_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn mức.
        /// </summary>
        internal static string lbl_minAmount {
            get {
                return ResourceManager.GetString("lbl_minAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc gia.
        /// </summary>
        internal static string lbl_nation {
            get {
                return ResourceManager.GetString("lbl_nation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email mới.
        /// </summary>
        internal static string lbl_newEmail {
            get {
                return ResourceManager.GetString("lbl_newEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string lbl_noteOTP_Email {
            get {
                return ResourceManager.GetString("lbl_noteOTP_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string lbl_noteOTP_SMS {
            get {
                return ResourceManager.GetString("lbl_noteOTP_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Ảnh up lên không quá 5MB.
        /// </summary>
        internal static string lbl_note_1 {
            get {
                return ResourceManager.GetString("lbl_note_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Không gửi quá 3 ảnh.
        /// </summary>
        internal static string lbl_note_2 {
            get {
                return ResourceManager.GetString("lbl_note_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không nhận được mã, vui lòng chọn &lt;span class=&quot;secondary&quot;&gt;Nhận lại OTP&lt;/span&gt;.
        /// </summary>
        internal static string lbl_note_3 {
            get {
                return ResourceManager.GetString("lbl_note_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Để chứng thực tài khoản, bạn phải gửi ảnh CMND/Passport để thực hiện  chứng thực..
        /// </summary>
        internal static string lbl_note_cetificate {
            get {
                return ResourceManager.GetString("lbl_note_cetificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ví điện tử.
        /// </summary>
        internal static string lbl_numberWallet {
            get {
                return ResourceManager.GetString("lbl_numberWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cũ.
        /// </summary>
        internal static string lbl_oldEmail {
            get {
                return ResourceManager.GetString("lbl_oldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực.
        /// </summary>
        internal static string lbl_otp {
            get {
                return ResourceManager.GetString("lbl_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMND.
        /// </summary>
        internal static string lbl_passport {
            get {
                return ResourceManager.GetString("lbl_passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        internal static string lbl_position {
            get {
                return ResourceManager.GetString("lbl_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức bảo mật.
        /// </summary>
        internal static string lbl_secureType {
            get {
                return ResourceManager.GetString("lbl_secureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gửi yêu cầu chứng thực.
        /// </summary>
        internal static string lbl_sendVerifyAccount {
            get {
                return ResourceManager.GetString("lbl_sendVerifyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        internal static string lbl_status {
            get {
                return ResourceManager.GetString("lbl_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã kích hoạt.
        /// </summary>
        internal static string lbl_status1 {
            get {
                return ResourceManager.GetString("lbl_status1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã chứng thực.
        /// </summary>
        internal static string lbl_status2 {
            get {
                return ResourceManager.GetString("lbl_status2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa kích hoạt.
        /// </summary>
        internal static string lbl_status3 {
            get {
                return ResourceManager.GetString("lbl_status3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực email.
        /// </summary>
        internal static string lbl_verifyEmail {
            get {
                return ResourceManager.GetString("lbl_verifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu ý.
        /// </summary>
        internal static string lbl_warning {
            get {
                return ResourceManager.GetString("lbl_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa xác thực email.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo mật thanh toán.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh Toán.
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo mật thanh toán.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xác thực email.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa chứng thực.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gửi yêu cầu.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã chứng thực.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa đăng ký.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa đăng ký bảo mật.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã đăng ký bảo mật.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhập ảnh đại diện.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực đã được gửi đến email.
        /// </summary>
        internal static string txt_sendOTP {
            get {
                return ResourceManager.GetString("txt_sendOTP", resourceCulture);
            }
        }
    }
}
