//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thẻ mới.
        /// </summary>
        internal static string addCard {
            get {
                return ResourceManager.GetString("addCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hà Nội (Trụ sở chính).
        /// </summary>
        internal static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP HCM.
        /// </summary>
        internal static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đà Nẵng.
        /// </summary>
        internal static string Address3 {
            get {
                return ResourceManager.GetString("Address3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string btn_confirm {
            get {
                return ResourceManager.GetString("btn_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất Excel.
        /// </summary>
        internal static string btn_excel {
            get {
                return ResourceManager.GetString("btn_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử giao dịch.
        /// </summary>
        internal static string btn_history {
            get {
                return ResourceManager.GetString("btn_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết thẻ.
        /// </summary>
        internal static string btn_linkCard {
            get {
                return ResourceManager.GetString("btn_linkCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        internal static string btn_news {
            get {
                return ResourceManager.GetString("btn_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In thường.
        /// </summary>
        internal static string btn_print {
            get {
                return ResourceManager.GetString("btn_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In nhiệt.
        /// </summary>
        internal static string btn_print1 {
            get {
                return ResourceManager.GetString("btn_print1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận lại.
        /// </summary>
        internal static string btn_receive {
            get {
                return ResourceManager.GetString("btn_receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string btn_search {
            get {
                return ResourceManager.GetString("btn_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        internal static string btn_SearchHistory {
            get {
                return ResourceManager.GetString("btn_SearchHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi Email.
        /// </summary>
        internal static string btn_SendEmail {
            get {
                return ResourceManager.GetString("btn_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi SMS.
        /// </summary>
        internal static string btn_sendSMS {
            get {
                return ResourceManager.GetString("btn_sendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tất cả.
        /// </summary>
        internal static string btn_showAll {
            get {
                return ResourceManager.GetString("btn_showAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem mã thẻ.
        /// </summary>
        internal static string btn_ShowCard {
            get {
                return ResourceManager.GetString("btn_ShowCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã bảo mật.
        /// </summary>
        internal static string enterOTP {
            get {
                return ResourceManager.GetString("enterOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn.
        /// </summary>
        internal static string guide_1 {
            get {
                return ResourceManager.GetString("guide_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi thường gặp.
        /// </summary>
        internal static string guide_10 {
            get {
                return ResourceManager.GetString("guide_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng liên hệ tổng đài theo số hotline để được trợ giúp.
        /// </summary>
        internal static string guide_11 {
            get {
                return ResourceManager.GetString("guide_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ví điện tử.
        /// </summary>
        internal static string guide_12 {
            get {
                return ResourceManager.GetString("guide_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua sắm.
        /// </summary>
        internal static string guide_13 {
            get {
                return ResourceManager.GetString("guide_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi có thể giúp gì cho bạn ?.
        /// </summary>
        internal static string guide_2 {
            get {
                return ResourceManager.GetString("guide_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nội dung cần hỗ trợ tại đây.
        /// </summary>
        internal static string guide_3 {
            get {
                return ResourceManager.GetString("guide_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn sử dụng.
        /// </summary>
        internal static string guide_4 {
            get {
                return ResourceManager.GetString("guide_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn đăng ký, chứng thực và bảo mật tài khoản.
        /// </summary>
        internal static string guide_5 {
            get {
                return ResourceManager.GetString("guide_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn nạp tiền, chuyển tiền, rút tiền.
        /// </summary>
        internal static string guide_6 {
            get {
                return ResourceManager.GetString("guide_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn mua hàng bằng ví điện tử.
        /// </summary>
        internal static string guide_7 {
            get {
                return ResourceManager.GetString("guide_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giải đáp các thắc mắc thường gặp của khách hàng.
        /// </summary>
        internal static string guide_8 {
            get {
                return ResourceManager.GetString("guide_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần trợ giúp trực tiếp.
        /// </summary>
        internal static string guide_9 {
            get {
                return ResourceManager.GetString("guide_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số 243A Đê La Thành. Hà Nội.
        /// </summary>
        internal static string lbl_AddressName {
            get {
                return ResourceManager.GetString("lbl_AddressName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngân Hàng.
        /// </summary>
        internal static string lbl_bank {
            get {
                return ResourceManager.GetString("lbl_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tất cả.
        /// </summary>
        internal static string lbl_chooseAll {
            get {
                return ResourceManager.GetString("lbl_chooseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ví điện tử Pay365.
        /// </summary>
        internal static string lbl_company {
            get {
                return ResourceManager.GetString("lbl_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Để chúng tôi có thể hỗ trợ bạn hiệu quả hơn, vui lòng gửi thông tin liên hệ theo mẫu sau.
        /// </summary>
        internal static string lbl_contact_note {
            get {
                return ResourceManager.GetString("lbl_contact_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp tác.
        /// </summary>
        internal static string lbl_corperation {
            get {
                return ResourceManager.GetString("lbl_corperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string lbl_Description {
            get {
                return ResourceManager.GetString("lbl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham khảo thêm.
        /// </summary>
        internal static string lbl_exploreMore {
            get {
                return ResourceManager.GetString("lbl_exploreMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ liên kết.
        /// </summary>
        internal static string lbl_linkCard {
            get {
                return ResourceManager.GetString("lbl_linkCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý thẻ liên kết.
        /// </summary>
        internal static string lbl_linkCard_Title {
            get {
                return ResourceManager.GetString("lbl_linkCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách bảo mật.
        /// </summary>
        internal static string lbl_privaryPolicy {
            get {
                return ResourceManager.GetString("lbl_privaryPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người nhận.
        /// </summary>
        internal static string lbl_ReceiveAcc {
            get {
                return ResourceManager.GetString("lbl_ReceiveAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem từ thẻ.
        /// </summary>
        internal static string lbl_showFrom {
            get {
                return ResourceManager.GetString("lbl_showFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem mã thẻ giao dịch.
        /// </summary>
        internal static string lbl_showNote {
            get {
                return ResourceManager.GetString("lbl_showNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to từ.
        /// </summary>
        internal static string lbl_showTo {
            get {
                return ResourceManager.GetString("lbl_showTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điều khoản sử dụng.
        /// </summary>
        internal static string lbl_termUse {
            get {
                return ResourceManager.GetString("lbl_termUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người chuyển.
        /// </summary>
        internal static string lbl_TransAcc {
            get {
                return ResourceManager.GetString("lbl_TransAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ và tài khoản ngân hàng.
        /// </summary>
        internal static string link_card {
            get {
                return ResourceManager.GetString("link_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        internal static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rút tiền.
        /// </summary>
        internal static string Menu_CashOut {
            get {
                return ResourceManager.GetString("Menu_CashOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string Menu_Contact {
            get {
                return ResourceManager.GetString("Menu_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        internal static string Menu_new {
            get {
                return ResourceManager.GetString("Menu_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ giúp.
        /// </summary>
        internal static string Menu_partner {
            get {
                return ResourceManager.GetString("Menu_partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách.
        /// </summary>
        internal static string Menu_privacy {
            get {
                return ResourceManager.GetString("Menu_privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp tiền.
        /// </summary>
        internal static string Menu_Topup {
            get {
                return ResourceManager.GetString("Menu_Topup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp qua ngân hàng.
        /// </summary>
        internal static string Menu_Topup1 {
            get {
                return ResourceManager.GetString("Menu_Topup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển tiền.
        /// </summary>
        internal static string Menu_Transfer {
            get {
                return ResourceManager.GetString("Menu_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp tiền điện thoại.
        /// </summary>
        internal static string Menu_Utility1 {
            get {
                return ResourceManager.GetString("Menu_Utility1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ điện thoại.
        /// </summary>
        internal static string Menu_Utility2 {
            get {
                return ResourceManager.GetString("Menu_Utility2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp tài khoản Game.
        /// </summary>
        internal static string Menu_Utility3 {
            get {
                return ResourceManager.GetString("Menu_Utility3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán hóa đơn.
        /// </summary>
        internal static string Menu_Utility4 {
            get {
                return ResourceManager.GetString("Menu_Utility4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ game.
        /// </summary>
        internal static string Menu_Utility5 {
            get {
                return ResourceManager.GetString("Menu_Utility5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không nhận được mã vui lòng click Nhận lại OTP hoặc soạn tin P365 OTP gửi 8100 (1.500 VNĐ/SMS).
        /// </summary>
        internal static string Noti_1 {
            get {
                return ResourceManager.GetString("Noti_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký bảo mật.
        /// </summary>
        internal static string registerOTP {
            get {
                return ResourceManager.GetString("registerOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thẻ đã chọn.
        /// </summary>
        internal static string SeeCard {
            get {
                return ResourceManager.GetString("SeeCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn mức.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đăng ký bảo mật.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi hạn mức.
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi thường gặp.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về chúng tôi.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiện ích.
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ.
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ.
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp tiền.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi liên hệ.
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung chi tiết.
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch thành công.
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch đang xử lý.
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ giúp khác.
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu.
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc.
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất Excel.
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rút tiền.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có giao dịch nào trong khoảng thời gian đã chọn.
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp tiền điện thoại.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ điện thoại.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp Tài khoản Game.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ game.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo mật.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức bảo mật.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giao dịch.
        /// </summary>
        internal static string TransactionID {
            get {
                return ResourceManager.GetString("TransactionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian GD.
        /// </summary>
        internal static string TransTime {
            get {
                return ResourceManager.GetString("TransTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản – Pay365.
        /// </summary>
        internal static string viewbag_accountInfo {
            get {
                return ResourceManager.GetString("viewbag_accountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua mã thẻ - Pay365.
        /// </summary>
        internal static string viewbag_buyCard {
            get {
                return ResourceManager.GetString("viewbag_buyCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rút tiền – Pay365.
        /// </summary>
        internal static string viewbag_cashout {
            get {
                return ResourceManager.GetString("viewbag_cashout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp game – Pay365.
        /// </summary>
        internal static string viewbag_GameTopup {
            get {
                return ResourceManager.GetString("viewbag_GameTopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ví điện tử- Cổng thanh toán điện tử Pay365.
        /// </summary>
        internal static string viewbag_layout_title {
            get {
                return ResourceManager.GetString("viewbag_layout_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức – Pay365.
        /// </summary>
        internal static string viewbag_news {
            get {
                return ResourceManager.GetString("viewbag_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp tiền điện thoại – Pay365.
        /// </summary>
        internal static string viewbag_telcoTopup {
            get {
                return ResourceManager.GetString("viewbag_telcoTopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp tiền – Pay365.
        /// </summary>
        internal static string viewbag_topup {
            get {
                return ResourceManager.GetString("viewbag_topup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển tiền – Pay365.
        /// </summary>
        internal static string viewbag_transfer {
            get {
                return ResourceManager.GetString("viewbag_transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ví điện tử Pay365.
        /// </summary>
        internal static string wallet_title {
            get {
                return ResourceManager.GetString("wallet_title", resourceCulture);
            }
        }
    }
}
