//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Payment {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Payment() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Payment", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        internal static string btnPayment {
            get {
                return ResourceManager.GetString("btnPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        internal static string btn_back {
            get {
                return ResourceManager.GetString("btn_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp theo.
        /// </summary>
        internal static string btn_next {
            get {
                return ResourceManager.GetString("btn_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận giao dịch.
        /// </summary>
        internal static string ConfirmTransaction {
            get {
                return ResourceManager.GetString("ConfirmTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất Excel.
        /// </summary>
        internal static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về trang chủ.
        /// </summary>
        internal static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản game.
        /// </summary>
        internal static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In thường.
        /// </summary>
        internal static string PrintNormal {
            get {
                return ResourceManager.GetString("PrintNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In nhiệt.
        /// </summary>
        internal static string PrintTemp {
            get {
                return ResourceManager.GetString("PrintTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn game.
        /// </summary>
        internal static string SelectGame {
            get {
                return ResourceManager.GetString("SelectGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi SMS.
        /// </summary>
        internal static string SendSMS {
            get {
                return ResourceManager.GetString("SendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý.
        /// </summary>
        internal static string status0 {
            get {
                return ResourceManager.GetString("status0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        internal static string status1 {
            get {
                return ResourceManager.GetString("status1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thất bại.
        /// </summary>
        internal static string status_fail {
            get {
                return ResourceManager.GetString("status_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các game đã nạp gần đây.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn mệnh giá.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm giá.
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch gần đây.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận giao dịch.
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán hóa đơn.
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ hay dùng gần đây.
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện.
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nước.
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toàn bộ game.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cước Internet.
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các thẻ đã mua gần đây.
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhà mạng.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin nạp tiền.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả trước.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả sau.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản game.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mệnh giá.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        internal static string table1 {
            get {
                return ResourceManager.GetString("table1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại thẻ.
        /// </summary>
        internal static string table2 {
            get {
                return ResourceManager.GetString("table2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mệnh giá thẻ.
        /// </summary>
        internal static string table3 {
            get {
                return ResourceManager.GetString("table3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã code.
        /// </summary>
        internal static string table4 {
            get {
                return ResourceManager.GetString("table4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial thẻ.
        /// </summary>
        internal static string table5 {
            get {
                return ResourceManager.GetString("table5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn sử dụng.
        /// </summary>
        internal static string table6 {
            get {
                return ResourceManager.GetString("table6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng mệnh giá.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch thành công.
        /// </summary>
        internal static string TransactionSuccess {
            get {
                return ResourceManager.GetString("TransactionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp tiền điện thoại.
        /// </summary>
        internal static string typeview1 {
            get {
                return ResourceManager.GetString("typeview1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp tài khoản game.
        /// </summary>
        internal static string typeview2 {
            get {
                return ResourceManager.GetString("typeview2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ điện thoại.
        /// </summary>
        internal static string typeview3 {
            get {
                return ResourceManager.GetString("typeview3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ game.
        /// </summary>
        internal static string typeview4 {
            get {
                return ResourceManager.GetString("typeview4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giao dịch.
        /// </summary>
        internal static string value1 {
            get {
                return ResourceManager.GetString("value1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng thanh toán.
        /// </summary>
        internal static string value10 {
            get {
                return ResourceManager.GetString("value10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương thức.
        /// </summary>
        internal static string value11 {
            get {
                return ResourceManager.GetString("value11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        internal static string value12 {
            get {
                return ResourceManager.GetString("value12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản nạp.
        /// </summary>
        internal static string value13 {
            get {
                return ResourceManager.GetString("value13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày giao dịch.
        /// </summary>
        internal static string value2 {
            get {
                return ResourceManager.GetString("value2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại giao dịch.
        /// </summary>
        internal static string value3 {
            get {
                return ResourceManager.GetString("value3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        internal static string value4 {
            get {
                return ResourceManager.GetString("value4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng.
        /// </summary>
        internal static string value5 {
            get {
                return ResourceManager.GetString("value5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mệnh giá.
        /// </summary>
        internal static string value6 {
            get {
                return ResourceManager.GetString("value6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền.
        /// </summary>
        internal static string value7 {
            get {
                return ResourceManager.GetString("value7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiết khấu.
        /// </summary>
        internal static string value8 {
            get {
                return ResourceManager.GetString("value8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí.
        /// </summary>
        internal static string value9 {
            get {
                return ResourceManager.GetString("value9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thẻ đã chọn.
        /// </summary>
        internal static string ViewCardSelected {
            get {
                return ResourceManager.GetString("ViewCardSelected", resourceCulture);
            }
        }
    }
}
