//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Topup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Topup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Topup", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chủ thẻ.
        /// </summary>
        internal static string account_holder {
            get {
                return ResourceManager.GetString("account_holder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp tiền.
        /// </summary>
        internal static string btn_Deposit {
            get {
                return ResourceManager.GetString("btn_Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản được nạp.
        /// </summary>
        internal static string deposit_account {
            get {
                return ResourceManager.GetString("deposit_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp tiền ví điện tử.
        /// </summary>
        internal static string lbl_depositWallet {
            get {
                return ResourceManager.GetString("lbl_depositWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch nạp tiền gần đây.
        /// </summary>
        internal static string lbl_recentlyDeposit {
            get {
                return ResourceManager.GetString("lbl_recentlyDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số thẻ.
        /// </summary>
        internal static string number_card {
            get {
                return ResourceManager.GetString("number_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí nạp.
        /// </summary>
        internal static string topup_fee {
            get {
                return ResourceManager.GetString("topup_fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành Tiền.
        /// </summary>
        internal static string topup_totalAmount {
            get {
                return ResourceManager.GetString("topup_totalAmount", resourceCulture);
            }
        }
    }
}
