//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Transfer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Transfer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Transfer", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền chuyển.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận giao dịch.
        /// </summary>
        internal static string lbl_confirmTransaction {
            get {
                return ResourceManager.GetString("lbl_confirmTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã xác thực.
        /// </summary>
        internal static string lbl_OTP {
            get {
                return ResourceManager.GetString("lbl_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển tiền.
        /// </summary>
        internal static string lbl_transferMoney {
            get {
                return ResourceManager.GetString("lbl_transferMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập OTP.
        /// </summary>
        internal static string OTP {
            get {
                return ResourceManager.GetString("OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản nhận.
        /// </summary>
        internal static string ReceiveAcc {
            get {
                return ResourceManager.GetString("ReceiveAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản nhận .
        /// </summary>
        internal static string ReceivedAcc {
            get {
                return ResourceManager.GetString("ReceivedAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản nhận.
        /// </summary>
        internal static string ReceivedAccname {
            get {
                return ResourceManager.GetString("ReceivedAccname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển tiền gần đây.
        /// </summary>
        internal static string RecentlyTrans {
            get {
                return ResourceManager.GetString("RecentlyTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng thanh toán.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí.
        /// </summary>
        internal static string TransFee {
            get {
                return ResourceManager.GetString("TransFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do chuyển.
        /// </summary>
        internal static string TransferReason {
            get {
                return ResourceManager.GetString("TransferReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chuyển.
        /// </summary>
        internal static string TransferredAcc {
            get {
                return ResourceManager.GetString("TransferredAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản chuyển.
        /// </summary>
        internal static string TransferredAccName {
            get {
                return ResourceManager.GetString("TransferredAccName", resourceCulture);
            }
        }
    }
}
