//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pay365.BillingReport.ReportService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankInfo", Namespace="http://schemas.datacontract.org/2004/07/DataAccess.OrdersAPI.DTO")]
    [System.SerializableAttribute()]
    public partial class BankInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BankFeeAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BankIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte BankTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkLogoMobileGridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkLogoMobileIconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoMobileGridField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoMobileIconField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PayServiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebSiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankCode {
            get {
                return this.BankCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BankCodeField, value) != true)) {
                    this.BankCodeField = value;
                    this.RaisePropertyChanged("BankCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BankFeeAmount {
            get {
                return this.BankFeeAmountField;
            }
            set {
                if ((this.BankFeeAmountField.Equals(value) != true)) {
                    this.BankFeeAmountField = value;
                    this.RaisePropertyChanged("BankFeeAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BankID {
            get {
                return this.BankIDField;
            }
            set {
                if ((this.BankIDField.Equals(value) != true)) {
                    this.BankIDField = value;
                    this.RaisePropertyChanged("BankID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte BankType {
            get {
                return this.BankTypeField;
            }
            set {
                if ((this.BankTypeField.Equals(value) != true)) {
                    this.BankTypeField = value;
                    this.RaisePropertyChanged("BankType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardColor {
            get {
                return this.CardColorField;
            }
            set {
                if ((object.ReferenceEquals(this.CardColorField, value) != true)) {
                    this.CardColorField = value;
                    this.RaisePropertyChanged("CardColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedTime {
            get {
                return this.CreatedTimeField;
            }
            set {
                if ((this.CreatedTimeField.Equals(value) != true)) {
                    this.CreatedTimeField = value;
                    this.RaisePropertyChanged("CreatedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkLogo {
            get {
                return this.LinkLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkLogoField, value) != true)) {
                    this.LinkLogoField = value;
                    this.RaisePropertyChanged("LinkLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkLogoMobileGrid {
            get {
                return this.LinkLogoMobileGridField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkLogoMobileGridField, value) != true)) {
                    this.LinkLogoMobileGridField = value;
                    this.RaisePropertyChanged("LinkLogoMobileGrid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkLogoMobileIcon {
            get {
                return this.LinkLogoMobileIconField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkLogoMobileIconField, value) != true)) {
                    this.LinkLogoMobileIconField = value;
                    this.RaisePropertyChanged("LinkLogoMobileIcon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logo {
            get {
                return this.LogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoField, value) != true)) {
                    this.LogoField = value;
                    this.RaisePropertyChanged("Logo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogoMobileGrid {
            get {
                return this.LogoMobileGridField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoMobileGridField, value) != true)) {
                    this.LogoMobileGridField = value;
                    this.RaisePropertyChanged("LogoMobileGrid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogoMobileIcon {
            get {
                return this.LogoMobileIconField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoMobileIconField, value) != true)) {
                    this.LogoMobileIconField = value;
                    this.RaisePropertyChanged("LogoMobileIcon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PayServiceID {
            get {
                return this.PayServiceIDField;
            }
            set {
                if ((this.PayServiceIDField.Equals(value) != true)) {
                    this.PayServiceIDField = value;
                    this.RaisePropertyChanged("PayServiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebSite {
            get {
                return this.WebSiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebSiteField, value) != true)) {
                    this.WebSiteField = value;
                    this.RaisePropertyChanged("WebSite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebsitePayment", Namespace="http://schemas.datacontract.org/2004/07/DataAccess.OrdersAPI.DTO")]
    [System.SerializableAttribute()]
    public partial class WebsitePayment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChargePackageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDatetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrivateKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PublicKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlNoitificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebLabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountID {
            get {
                return this.AccountIDField;
            }
            set {
                if ((this.AccountIDField.Equals(value) != true)) {
                    this.AccountIDField = value;
                    this.RaisePropertyChanged("AccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChargePackageID {
            get {
                return this.ChargePackageIDField;
            }
            set {
                if ((this.ChargePackageIDField.Equals(value) != true)) {
                    this.ChargePackageIDField = value;
                    this.RaisePropertyChanged("ChargePackageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDatetime {
            get {
                return this.CreatedDatetimeField;
            }
            set {
                if ((this.CreatedDatetimeField.Equals(value) != true)) {
                    this.CreatedDatetimeField = value;
                    this.RaisePropertyChanged("CreatedDatetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkLogo {
            get {
                return this.LinkLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkLogoField, value) != true)) {
                    this.LinkLogoField = value;
                    this.RaisePropertyChanged("LinkLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logo {
            get {
                return this.LogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoField, value) != true)) {
                    this.LogoField = value;
                    this.RaisePropertyChanged("Logo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrivateKey {
            get {
                return this.PrivateKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivateKeyField, value) != true)) {
                    this.PrivateKeyField = value;
                    this.RaisePropertyChanged("PrivateKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PublicKey {
            get {
                return this.PublicKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PublicKeyField, value) != true)) {
                    this.PublicKeyField = value;
                    this.RaisePropertyChanged("PublicKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlNoitification {
            get {
                return this.UrlNoitificationField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlNoitificationField, value) != true)) {
                    this.UrlNoitificationField = value;
                    this.RaisePropertyChanged("UrlNoitification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlReturn {
            get {
                return this.UrlReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlReturnField, value) != true)) {
                    this.UrlReturnField = value;
                    this.RaisePropertyChanged("UrlReturn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebLabel {
            get {
                return this.WebLabelField;
            }
            set {
                if ((object.ReferenceEquals(this.WebLabelField, value) != true)) {
                    this.WebLabelField = value;
                    this.RaisePropertyChanged("WebLabel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebName {
            get {
                return this.WebNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WebNameField, value) != true)) {
                    this.WebNameField = value;
                    this.RaisePropertyChanged("WebName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportService.IReportService")]
    public interface IReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetListBankForCashOut", ReplyAction="http://tempuri.org/IReportService/GetListBankForCashOutResponse")]
        Pay365.BillingReport.ReportService.BankInfo[] GetListBankForCashOut(byte bankType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetListBankForCashOut", ReplyAction="http://tempuri.org/IReportService/GetListBankForCashOutResponse")]
        System.Threading.Tasks.Task<Pay365.BillingReport.ReportService.BankInfo[]> GetListBankForCashOutAsync(byte bankType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetListBankTopup", ReplyAction="http://tempuri.org/IReportService/GetListBankTopupResponse")]
        Pay365.BillingReport.ReportService.BankInfo[] GetListBankTopup(byte bankType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetListBankTopup", ReplyAction="http://tempuri.org/IReportService/GetListBankTopupResponse")]
        System.Threading.Tasks.Task<Pay365.BillingReport.ReportService.BankInfo[]> GetListBankTopupAsync(byte bankType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/BankInfo_GetByCondition", ReplyAction="http://tempuri.org/IReportService/BankInfo_GetByConditionResponse")]
        Pay365.BillingReport.ReportService.BankInfo[] BankInfo_GetByCondition(int bankId, string bankCode, string bankName, byte bankType, byte status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/BankInfo_GetByCondition", ReplyAction="http://tempuri.org/IReportService/BankInfo_GetByConditionResponse")]
        System.Threading.Tasks.Task<Pay365.BillingReport.ReportService.BankInfo[]> BankInfo_GetByConditionAsync(int bankId, string bankCode, string bankName, byte bankType, byte status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/WebsitePayment_GetList", ReplyAction="http://tempuri.org/IReportService/WebsitePayment_GetListResponse")]
        Pay365.BillingReport.ReportService.WebsitePayment[] WebsitePayment_GetList(int AccountID, int WebsiteID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/WebsitePayment_GetList", ReplyAction="http://tempuri.org/IReportService/WebsitePayment_GetListResponse")]
        System.Threading.Tasks.Task<Pay365.BillingReport.ReportService.WebsitePayment[]> WebsitePayment_GetListAsync(int AccountID, int WebsiteID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportServiceChannel : Pay365.BillingReport.ReportService.IReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<Pay365.BillingReport.ReportService.IReportService>, Pay365.BillingReport.ReportService.IReportService {
        
        public ReportServiceClient() {
        }
        
        public ReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pay365.BillingReport.ReportService.BankInfo[] GetListBankForCashOut(byte bankType) {
            return base.Channel.GetListBankForCashOut(bankType);
        }
        
        public System.Threading.Tasks.Task<Pay365.BillingReport.ReportService.BankInfo[]> GetListBankForCashOutAsync(byte bankType) {
            return base.Channel.GetListBankForCashOutAsync(bankType);
        }
        
        public Pay365.BillingReport.ReportService.BankInfo[] GetListBankTopup(byte bankType) {
            return base.Channel.GetListBankTopup(bankType);
        }
        
        public System.Threading.Tasks.Task<Pay365.BillingReport.ReportService.BankInfo[]> GetListBankTopupAsync(byte bankType) {
            return base.Channel.GetListBankTopupAsync(bankType);
        }
        
        public Pay365.BillingReport.ReportService.BankInfo[] BankInfo_GetByCondition(int bankId, string bankCode, string bankName, byte bankType, byte status) {
            return base.Channel.BankInfo_GetByCondition(bankId, bankCode, bankName, bankType, status);
        }
        
        public System.Threading.Tasks.Task<Pay365.BillingReport.ReportService.BankInfo[]> BankInfo_GetByConditionAsync(int bankId, string bankCode, string bankName, byte bankType, byte status) {
            return base.Channel.BankInfo_GetByConditionAsync(bankId, bankCode, bankName, bankType, status);
        }
        
        public Pay365.BillingReport.ReportService.WebsitePayment[] WebsitePayment_GetList(int AccountID, int WebsiteID) {
            return base.Channel.WebsitePayment_GetList(AccountID, WebsiteID);
        }
        
        public System.Threading.Tasks.Task<Pay365.BillingReport.ReportService.WebsitePayment[]> WebsitePayment_GetListAsync(int AccountID, int WebsiteID) {
            return base.Channel.WebsitePayment_GetListAsync(AccountID, WebsiteID);
        }
    }
}
