//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pay365.BillingReport.VTCProService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VTCProCard_UseCard_MerchantPayment", Namespace="http://schemas.datacontract.org/2004/07/DataAccess.VTCProAPI.DTO")]
    [System.SerializableAttribute()]
    public partial class VTCProCard_UseCard_MerchantPayment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CardAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CardSerialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedFullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long GrandAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MerchantAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MerchantFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantTransactionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TransactionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UserTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CardAmount {
            get {
                return this.CardAmountField;
            }
            set {
                if ((this.CardAmountField.Equals(value) != true)) {
                    this.CardAmountField = value;
                    this.RaisePropertyChanged("CardAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CardSerial {
            get {
                return this.CardSerialField;
            }
            set {
                if ((this.CardSerialField.Equals(value) != true)) {
                    this.CardSerialField = value;
                    this.RaisePropertyChanged("CardSerial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedAccount {
            get {
                return this.CreatedAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedAccountField, value) != true)) {
                    this.CreatedAccountField = value;
                    this.RaisePropertyChanged("CreatedAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedFullname {
            get {
                return this.CreatedFullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedFullnameField, value) != true)) {
                    this.CreatedFullnameField = value;
                    this.RaisePropertyChanged("CreatedFullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedTime {
            get {
                return this.CreatedTimeField;
            }
            set {
                if ((this.CreatedTimeField.Equals(value) != true)) {
                    this.CreatedTimeField = value;
                    this.RaisePropertyChanged("CreatedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long GrandAmount {
            get {
                return this.GrandAmountField;
            }
            set {
                if ((this.GrandAmountField.Equals(value) != true)) {
                    this.GrandAmountField = value;
                    this.RaisePropertyChanged("GrandAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MerchantAmount {
            get {
                return this.MerchantAmountField;
            }
            set {
                if ((this.MerchantAmountField.Equals(value) != true)) {
                    this.MerchantAmountField = value;
                    this.RaisePropertyChanged("MerchantAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantCode {
            get {
                return this.MerchantCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantCodeField, value) != true)) {
                    this.MerchantCodeField = value;
                    this.RaisePropertyChanged("MerchantCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MerchantFee {
            get {
                return this.MerchantFeeField;
            }
            set {
                if ((this.MerchantFeeField.Equals(value) != true)) {
                    this.MerchantFeeField = value;
                    this.RaisePropertyChanged("MerchantFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantTransactionCode {
            get {
                return this.MerchantTransactionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantTransactionCodeField, value) != true)) {
                    this.MerchantTransactionCodeField = value;
                    this.RaisePropertyChanged("MerchantTransactionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveAccount {
            get {
                return this.ReceiveAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveAccountField, value) != true)) {
                    this.ReceiveAccountField = value;
                    this.RaisePropertyChanged("ReceiveAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseDesc {
            get {
                return this.ResponseDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseDescField, value) != true)) {
                    this.ResponseDescField = value;
                    this.RaisePropertyChanged("ResponseDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseStatus {
            get {
                return this.ResponseStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseStatusField, value) != true)) {
                    this.ResponseStatusField = value;
                    this.RaisePropertyChanged("ResponseStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((this.TransactionIDField.Equals(value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UserTime {
            get {
                return this.UserTimeField;
            }
            set {
                if ((this.UserTimeField.Equals(value) != true)) {
                    this.UserTimeField = value;
                    this.RaisePropertyChanged("UserTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VTCProCard_UseCard_History", Namespace="http://schemas.datacontract.org/2004/07/DataAccess.VTCProAPI.DTO")]
    [System.SerializableAttribute()]
    public partial class VTCProCard_UseCard_History : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CardAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CardSerialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedFullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UserTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CardAmount {
            get {
                return this.CardAmountField;
            }
            set {
                if ((this.CardAmountField.Equals(value) != true)) {
                    this.CardAmountField = value;
                    this.RaisePropertyChanged("CardAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CardSerial {
            get {
                return this.CardSerialField;
            }
            set {
                if ((this.CardSerialField.Equals(value) != true)) {
                    this.CardSerialField = value;
                    this.RaisePropertyChanged("CardSerial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedAccount {
            get {
                return this.CreatedAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedAccountField, value) != true)) {
                    this.CreatedAccountField = value;
                    this.RaisePropertyChanged("CreatedAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedFullname {
            get {
                return this.CreatedFullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedFullnameField, value) != true)) {
                    this.CreatedFullnameField = value;
                    this.RaisePropertyChanged("CreatedFullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantCode {
            get {
                return this.MerchantCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantCodeField, value) != true)) {
                    this.MerchantCodeField = value;
                    this.RaisePropertyChanged("MerchantCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveAccount {
            get {
                return this.ReceiveAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveAccountField, value) != true)) {
                    this.ReceiveAccountField = value;
                    this.RaisePropertyChanged("ReceiveAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseStatus {
            get {
                return this.ResponseStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseStatusField, value) != true)) {
                    this.ResponseStatusField = value;
                    this.RaisePropertyChanged("ResponseStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UserTime {
            get {
                return this.UserTimeField;
            }
            set {
                if ((this.UserTimeField.Equals(value) != true)) {
                    this.UserTimeField = value;
                    this.RaisePropertyChanged("UserTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportGeneral", Namespace="http://schemas.datacontract.org/2004/07/DataAccess.VTCProAPI.DTO")]
    [System.SerializableAttribute()]
    public partial class ReportGeneral : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReportDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalCreateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalCreateAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalExpiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalMaintainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalMaintainAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalPaymentAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalUseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReportDate {
            get {
                return this.ReportDateField;
            }
            set {
                if ((this.ReportDateField.Equals(value) != true)) {
                    this.ReportDateField = value;
                    this.RaisePropertyChanged("ReportDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalCreate {
            get {
                return this.TotalCreateField;
            }
            set {
                if ((this.TotalCreateField.Equals(value) != true)) {
                    this.TotalCreateField = value;
                    this.RaisePropertyChanged("TotalCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalCreateAmount {
            get {
                return this.TotalCreateAmountField;
            }
            set {
                if ((this.TotalCreateAmountField.Equals(value) != true)) {
                    this.TotalCreateAmountField = value;
                    this.RaisePropertyChanged("TotalCreateAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalExpired {
            get {
                return this.TotalExpiredField;
            }
            set {
                if ((this.TotalExpiredField.Equals(value) != true)) {
                    this.TotalExpiredField = value;
                    this.RaisePropertyChanged("TotalExpired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalMaintain {
            get {
                return this.TotalMaintainField;
            }
            set {
                if ((this.TotalMaintainField.Equals(value) != true)) {
                    this.TotalMaintainField = value;
                    this.RaisePropertyChanged("TotalMaintain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalMaintainAmount {
            get {
                return this.TotalMaintainAmountField;
            }
            set {
                if ((this.TotalMaintainAmountField.Equals(value) != true)) {
                    this.TotalMaintainAmountField = value;
                    this.RaisePropertyChanged("TotalMaintainAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalPaymentAmount {
            get {
                return this.TotalPaymentAmountField;
            }
            set {
                if ((this.TotalPaymentAmountField.Equals(value) != true)) {
                    this.TotalPaymentAmountField = value;
                    this.RaisePropertyChanged("TotalPaymentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalUse {
            get {
                return this.TotalUseField;
            }
            set {
                if ((this.TotalUseField.Equals(value) != true)) {
                    this.TotalUseField = value;
                    this.RaisePropertyChanged("TotalUse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportCreate", Namespace="http://schemas.datacontract.org/2004/07/DataAccess.VTCProAPI.DTO")]
    [System.SerializableAttribute()]
    public partial class ReportCreate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CardAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CardFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CardSerialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedFullnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CardAmount {
            get {
                return this.CardAmountField;
            }
            set {
                if ((this.CardAmountField.Equals(value) != true)) {
                    this.CardAmountField = value;
                    this.RaisePropertyChanged("CardAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CardFee {
            get {
                return this.CardFeeField;
            }
            set {
                if ((this.CardFeeField.Equals(value) != true)) {
                    this.CardFeeField = value;
                    this.RaisePropertyChanged("CardFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CardSerial {
            get {
                return this.CardSerialField;
            }
            set {
                if ((this.CardSerialField.Equals(value) != true)) {
                    this.CardSerialField = value;
                    this.RaisePropertyChanged("CardSerial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedAccount {
            get {
                return this.CreatedAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedAccountField, value) != true)) {
                    this.CreatedAccountField = value;
                    this.RaisePropertyChanged("CreatedAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedFullname {
            get {
                return this.CreatedFullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedFullnameField, value) != true)) {
                    this.CreatedFullnameField = value;
                    this.RaisePropertyChanged("CreatedFullname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VTCPro_UseCardInfo", Namespace="http://schemas.datacontract.org/2004/07/DataAccess.VTCProAPI.DTO")]
    [System.SerializableAttribute()]
    public partial class VTCPro_UseCardInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CardAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CardStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardStatusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CardValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpiredDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpiredDateCurentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FeeAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TransactionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UseTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CardAmount {
            get {
                return this.CardAmountField;
            }
            set {
                if ((this.CardAmountField.Equals(value) != true)) {
                    this.CardAmountField = value;
                    this.RaisePropertyChanged("CardAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CardStatus {
            get {
                return this.CardStatusField;
            }
            set {
                if ((this.CardStatusField.Equals(value) != true)) {
                    this.CardStatusField = value;
                    this.RaisePropertyChanged("CardStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardStatusName {
            get {
                return this.CardStatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CardStatusNameField, value) != true)) {
                    this.CardStatusNameField = value;
                    this.RaisePropertyChanged("CardStatusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CardValue {
            get {
                return this.CardValueField;
            }
            set {
                if ((this.CardValueField.Equals(value) != true)) {
                    this.CardValueField = value;
                    this.RaisePropertyChanged("CardValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpiredDate {
            get {
                return this.ExpiredDateField;
            }
            set {
                if ((this.ExpiredDateField.Equals(value) != true)) {
                    this.ExpiredDateField = value;
                    this.RaisePropertyChanged("ExpiredDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpiredDateCurent {
            get {
                return this.ExpiredDateCurentField;
            }
            set {
                if ((this.ExpiredDateCurentField.Equals(value) != true)) {
                    this.ExpiredDateCurentField = value;
                    this.RaisePropertyChanged("ExpiredDateCurent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FeeAmount {
            get {
                return this.FeeAmountField;
            }
            set {
                if ((this.FeeAmountField.Equals(value) != true)) {
                    this.FeeAmountField = value;
                    this.RaisePropertyChanged("FeeAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantAccount {
            get {
                return this.MerchantAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantAccountField, value) != true)) {
                    this.MerchantAccountField = value;
                    this.RaisePropertyChanged("MerchantAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantCode {
            get {
                return this.MerchantCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantCodeField, value) != true)) {
                    this.MerchantCodeField = value;
                    this.RaisePropertyChanged("MerchantCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransactionID {
            get {
                return this.TransactionIDField;
            }
            set {
                if ((this.TransactionIDField.Equals(value) != true)) {
                    this.TransactionIDField = value;
                    this.RaisePropertyChanged("TransactionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UseTime {
            get {
                return this.UseTimeField;
            }
            set {
                if ((this.UseTimeField.Equals(value) != true)) {
                    this.UseTimeField = value;
                    this.RaisePropertyChanged("UseTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestData", Namespace="http://schemas.datacontract.org/2004/07/VTCApp.AdminService.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Pay365.BillingReport.VTCProService.Card_BlockUnblockRequestData))]
    public partial class RequestData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sign {
            get {
                return this.SignField;
            }
            set {
                if ((object.ReferenceEquals(this.SignField, value) != true)) {
                    this.SignField = value;
                    this.RaisePropertyChanged("Sign");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card_BlockUnblockRequestData", Namespace="http://schemas.datacontract.org/2004/07/VTCApp.AdminService.Models")]
    [System.SerializableAttribute()]
    public partial class Card_BlockUnblockRequestData : Pay365.BillingReport.VTCProService.RequestData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CardSerialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserConfirmField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CardSerial {
            get {
                return this.CardSerialField;
            }
            set {
                if ((this.CardSerialField.Equals(value) != true)) {
                    this.CardSerialField = value;
                    this.RaisePropertyChanged("CardSerial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserConfirm {
            get {
                return this.UserConfirmField;
            }
            set {
                if ((object.ReferenceEquals(this.UserConfirmField, value) != true)) {
                    this.UserConfirmField = value;
                    this.RaisePropertyChanged("UserConfirm");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseData", Namespace="http://schemas.datacontract.org/2004/07/VTCApp.AdminService.Models")]
    [System.SerializableAttribute()]
    public partial class ResponseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResponseCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extend {
            get {
                return this.ExtendField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendField, value) != true)) {
                    this.ExtendField = value;
                    this.RaisePropertyChanged("Extend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((this.ResponseCodeField.Equals(value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Merchant", Namespace="http://schemas.datacontract.org/2004/07/DataAccess.VTCProAPI.DTO")]
    [System.SerializableAttribute()]
    public partial class Merchant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MerchantAccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MerchantIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MerchantNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantAccount {
            get {
                return this.MerchantAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantAccountField, value) != true)) {
                    this.MerchantAccountField = value;
                    this.RaisePropertyChanged("MerchantAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MerchantAccountID {
            get {
                return this.MerchantAccountIDField;
            }
            set {
                if ((this.MerchantAccountIDField.Equals(value) != true)) {
                    this.MerchantAccountIDField = value;
                    this.RaisePropertyChanged("MerchantAccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantCode {
            get {
                return this.MerchantCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantCodeField, value) != true)) {
                    this.MerchantCodeField = value;
                    this.RaisePropertyChanged("MerchantCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MerchantID {
            get {
                return this.MerchantIDField;
            }
            set {
                if ((this.MerchantIDField.Equals(value) != true)) {
                    this.MerchantIDField = value;
                    this.RaisePropertyChanged("MerchantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantKey {
            get {
                return this.MerchantKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantKeyField, value) != true)) {
                    this.MerchantKeyField = value;
                    this.RaisePropertyChanged("MerchantKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MerchantName {
            get {
                return this.MerchantNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantNameField, value) != true)) {
                    this.MerchantNameField = value;
                    this.RaisePropertyChanged("MerchantName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VTCProService.IVTCProService")]
    public interface IVTCProService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVTCProService/VTCPro_UseCard_MerchantPayment_GetList", ReplyAction="http://tempuri.org/IVTCProService/VTCPro_UseCard_MerchantPayment_GetListResponse")]
        Pay365.BillingReport.VTCProService.VTCProCard_UseCard_MerchantPayment[] VTCPro_UseCard_MerchantPayment_GetList(string merchantCode, long cardSerial, string cardCode, long cardAmount, int status, long transactionID, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVTCProService/VTCPro_UseCard_MerchantPayment_GetList", ReplyAction="http://tempuri.org/IVTCProService/VTCPro_UseCard_MerchantPayment_GetListResponse")]
        System.Threading.Tasks.Task<Pay365.BillingReport.VTCProService.VTCProCard_UseCard_MerchantPayment[]> VTCPro_UseCard_MerchantPayment_GetListAsync(string merchantCode, long cardSerial, string cardCode, long cardAmount, int status, long transactionID, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVTCProService/VTCPro_UseCard_History_GetList", ReplyAction="http://tempuri.org/IVTCProService/VTCPro_UseCard_History_GetListResponse")]
        Pay365.BillingReport.VTCProService.VTCProCard_UseCard_History[] VTCPro_UseCard_History_GetList(string createdAccount, string merchantAccount, long cardSerial, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVTCProService/VTCPro_UseCard_History_GetList", ReplyAction="http://tempuri.org/IVTCProService/VTCPro_UseCard_History_GetListResponse")]
        System.Threading.Tasks.Task<Pay365.BillingReport.VTCProService.VTCProCard_UseCard_History[]> VTCPro_UseCard_History_GetListAsync(string createdAccount, string merchantAccount, long cardSerial, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVTCProService/VTCPro_ReportGeneral", ReplyAction="http://tempuri.org/IVTCProService/VTCPro_ReportGeneralResponse")]
        Pay365.BillingReport.VTCProService.ReportGeneral[] VTCPro_ReportGeneral(System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVTCProService/VTCPro_ReportGeneral", ReplyAction="http://tempuri.org/IVTCProService/VTCPro_ReportGeneralResponse")]
        System.Threading.Tasks.Task<Pay365.BillingReport.VTCProService.ReportGeneral[]> VTCPro_ReportGeneralAsync(System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVTCProService/VTCPro_ReportCreate", ReplyAction="http://tempuri.org/IVTCProService/VTCPro_ReportCreateResponse")]
        Pay365.BillingReport.VTCProService.ReportCreate[] VTCPro_ReportCreate(System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVTCProService/VTCPro_ReportCreate", ReplyAction="http://tempuri.org/IVTCProService/VTCPro_ReportCreateResponse")]
        System.Threading.Tasks.Task<Pay365.BillingReport.VTCProService.ReportCreate[]> VTCPro_ReportCreateAsync(System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVTCProService/VTCPro_UseCard_GetInfoBySerial", ReplyAction="http://tempuri.org/IVTCProService/VTCPro_UseCard_GetInfoBySerialResponse")]
        Pay365.BillingReport.VTCProService.VTCPro_UseCardInfo VTCPro_UseCard_GetInfoBySerial(long cardSerial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVTCProService/VTCPro_UseCard_GetInfoBySerial", ReplyAction="http://tempuri.org/IVTCProService/VTCPro_UseCard_GetInfoBySerialResponse")]
        System.Threading.Tasks.Task<Pay365.BillingReport.VTCProService.VTCPro_UseCardInfo> VTCPro_UseCard_GetInfoBySerialAsync(long cardSerial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVTCProService/CardData_BlockUnblock", ReplyAction="http://tempuri.org/IVTCProService/CardData_BlockUnblockResponse")]
        Pay365.BillingReport.VTCProService.ResponseData CardData_BlockUnblock(Pay365.BillingReport.VTCProService.Card_BlockUnblockRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVTCProService/CardData_BlockUnblock", ReplyAction="http://tempuri.org/IVTCProService/CardData_BlockUnblockResponse")]
        System.Threading.Tasks.Task<Pay365.BillingReport.VTCProService.ResponseData> CardData_BlockUnblockAsync(Pay365.BillingReport.VTCProService.Card_BlockUnblockRequestData requestData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVTCProService/Merchant_Getlist", ReplyAction="http://tempuri.org/IVTCProService/Merchant_GetlistResponse")]
        Pay365.BillingReport.VTCProService.Merchant[] Merchant_Getlist();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVTCProService/Merchant_Getlist", ReplyAction="http://tempuri.org/IVTCProService/Merchant_GetlistResponse")]
        System.Threading.Tasks.Task<Pay365.BillingReport.VTCProService.Merchant[]> Merchant_GetlistAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVTCProServiceChannel : Pay365.BillingReport.VTCProService.IVTCProService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VTCProServiceClient : System.ServiceModel.ClientBase<Pay365.BillingReport.VTCProService.IVTCProService>, Pay365.BillingReport.VTCProService.IVTCProService {
        
        public VTCProServiceClient() {
        }
        
        public VTCProServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VTCProServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VTCProServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VTCProServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pay365.BillingReport.VTCProService.VTCProCard_UseCard_MerchantPayment[] VTCPro_UseCard_MerchantPayment_GetList(string merchantCode, long cardSerial, string cardCode, long cardAmount, int status, long transactionID, System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.VTCPro_UseCard_MerchantPayment_GetList(merchantCode, cardSerial, cardCode, cardAmount, status, transactionID, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<Pay365.BillingReport.VTCProService.VTCProCard_UseCard_MerchantPayment[]> VTCPro_UseCard_MerchantPayment_GetListAsync(string merchantCode, long cardSerial, string cardCode, long cardAmount, int status, long transactionID, System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.VTCPro_UseCard_MerchantPayment_GetListAsync(merchantCode, cardSerial, cardCode, cardAmount, status, transactionID, fromDate, toDate);
        }
        
        public Pay365.BillingReport.VTCProService.VTCProCard_UseCard_History[] VTCPro_UseCard_History_GetList(string createdAccount, string merchantAccount, long cardSerial, System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.VTCPro_UseCard_History_GetList(createdAccount, merchantAccount, cardSerial, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<Pay365.BillingReport.VTCProService.VTCProCard_UseCard_History[]> VTCPro_UseCard_History_GetListAsync(string createdAccount, string merchantAccount, long cardSerial, System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.VTCPro_UseCard_History_GetListAsync(createdAccount, merchantAccount, cardSerial, fromDate, toDate);
        }
        
        public Pay365.BillingReport.VTCProService.ReportGeneral[] VTCPro_ReportGeneral(System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.VTCPro_ReportGeneral(fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<Pay365.BillingReport.VTCProService.ReportGeneral[]> VTCPro_ReportGeneralAsync(System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.VTCPro_ReportGeneralAsync(fromDate, toDate);
        }
        
        public Pay365.BillingReport.VTCProService.ReportCreate[] VTCPro_ReportCreate(System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.VTCPro_ReportCreate(fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<Pay365.BillingReport.VTCProService.ReportCreate[]> VTCPro_ReportCreateAsync(System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.VTCPro_ReportCreateAsync(fromDate, toDate);
        }
        
        public Pay365.BillingReport.VTCProService.VTCPro_UseCardInfo VTCPro_UseCard_GetInfoBySerial(long cardSerial) {
            return base.Channel.VTCPro_UseCard_GetInfoBySerial(cardSerial);
        }
        
        public System.Threading.Tasks.Task<Pay365.BillingReport.VTCProService.VTCPro_UseCardInfo> VTCPro_UseCard_GetInfoBySerialAsync(long cardSerial) {
            return base.Channel.VTCPro_UseCard_GetInfoBySerialAsync(cardSerial);
        }
        
        public Pay365.BillingReport.VTCProService.ResponseData CardData_BlockUnblock(Pay365.BillingReport.VTCProService.Card_BlockUnblockRequestData requestData) {
            return base.Channel.CardData_BlockUnblock(requestData);
        }
        
        public System.Threading.Tasks.Task<Pay365.BillingReport.VTCProService.ResponseData> CardData_BlockUnblockAsync(Pay365.BillingReport.VTCProService.Card_BlockUnblockRequestData requestData) {
            return base.Channel.CardData_BlockUnblockAsync(requestData);
        }
        
        public Pay365.BillingReport.VTCProService.Merchant[] Merchant_Getlist() {
            return base.Channel.Merchant_Getlist();
        }
        
        public System.Threading.Tasks.Task<Pay365.BillingReport.VTCProService.Merchant[]> Merchant_GetlistAsync() {
            return base.Channel.Merchant_GetlistAsync();
        }
    }
}
